[package]
name = "guessing_game"
version = "0.1.0"
edition = "2024"


# Crates in the Rust ecosystem are at crates.io
[dependencies]
# Using Semantic Versioning (SemVer): ^0.8.5 means any version >=0.8.5 but <0.9.0
rand = "0.8.5"